apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "suite-svc-register.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "suite-svc-register.name" . }}
    chart: {{ template "suite-svc-register.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "suite-svc-register.name" . }}
  namespace: {{ .Values.global.namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "suite-svc-register.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "suite-svc-register.name" . }}
    chart: {{ template "suite-svc-register.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "suite-svc-register.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "suite-svc-register.name" . }}
  namespace: {{ .Values.global.namespace }}

