{{- if .Values.global.suiteLogging }}
apiVersion: v1
kind: Service
metadata:
  name: suite-logging-elasticsearch-2
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    role: client
spec:
  type: {{ .Values.common.service2Type }}
  selector:
    component: {{ template "fullname" . }}
    role: client
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: {{ .Values.service.transportPort }}
    targetPort: 9300
    protocol: TCP
{{- end -}}
