{{- if .Values.global.suiteLogging }}
{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: suite-kibana
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}-kibana
spec:
  type: {{ .Values.kibana.serviceType }}
  ports:
  - port: {{ .Values.kibana.httpPort }}
    targetPort: 5601
    protocol: TCP
  selector:
    component: {{ template "fullname" . }}-kibana
{{- end }}
{{- end -}}
