apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "suite-mng.fullname" . }}
  labels:
    app: {{ template "suite-mng.name" . }}
    chart: {{ template "suite-mng.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "suite-mng.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "suite-mng.fullname" . }}
  labels:
    app: {{ template "suite-mng.name" . }}
    chart: {{ template "suite-mng.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "suite-mng.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "suite-mng.fullname" . }}

