{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: suite-random-password
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-failed
  labels:
    app: {{ template "suite-common.name" . }}
    chart: {{ template "suite-common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
