dependencies:
- name: suite-prod-mgmt
  version: ">=0.0.0-0"
  repository: "https://repo.ci.ciscolabs.com/CPSG_wakanda/charts/postmerge"
- name: suite-svc-register
  version: ">=0.0.0-0"
  repository: "https://repo.ci.ciscolabs.com/CPSG_wakanda/charts/postmerge"
- name: suite-common
  version: ">=0.0.0-0"
  repository: "https://repo.ci.ciscolabs.com/CPSG_quicksilver/charts/postmerge"
- name: ui
  version: ">=0.0.0-0"
  repository: "https://repo.ci.ciscolabs.com/CPSG_suiteadmin/charts/postmerge"
- name: suite-k8s-mgmt
  version: ">=0.0.0-0"
  repository: "https://repo.ci.ciscolabs.com/CPSG_wakanda/charts/postmerge"
  condition: global.launchedByInstaller
