apiVersion: v1
kind: Service
metadata:
  name: {{ template "suite-nats.name" . }}
  labels:
    app: {{ template "suite-nats.name" . }}
    chart: {{ template "suite-nats.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: suite-nats
spec:
  # type: { .Values.service.type }
  # Headless Service
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
  selector:
    component: suite-nats
    app: {{ template "suite-nats.name" . }}
    release: {{ .Release.Name }}
