apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    release: {{ .Release.Name }}
  name: suite-monitoring-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    release: {{ .Release.Name }}
  name: suite-monitoring-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: suite-monitoring-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cluster-admin