apiVersion: v1
kind: Service
metadata:
  name: {{ template "suite-demo-hello.name" . }}
  labels:
    app: {{ template "suite-demo-hello.name" . }}
    chart: {{ template "suite-demo-hello.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "suite-demo-hello.name" . }}
    release: {{ .Release.Name }}
